# The URL the site will be built for
base_url = "https://bugkrusha.github.io/bkdc"

# The site title and description
title = "Bug Krusha"
description = "Code, research, and technical insights"

# The default language; used in feeds and search index
default_language = "en"

# Define taxonomies
taxonomies = [
    {name = "tags", feed = true},
]

# Theme to use (leave empty for custom)
# theme = ""

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Configuration of the Markdown rendering
[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlighting = true
highlight_theme = "base16-ocean-dark"
render_emoji = false
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

# Configuration of the link checker.
[link_checker]
# Skip link checking for external URLs that start with these prefixes
skip_prefixes = [
    "http://[2001:db8::]/",
]

# Various slugification strategies, see below for details
# Defaults to everything being a slug
[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
# Put all your custom variables here
author = "Jazbo Beason"
show_reading_time = true